apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echo
  namespace: mjafary
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: echo
    spec:
      containers:
      - resources:
        name: echo
        image: jafary/echo:v2
        ports:
        - name: echo-port
          containerPort: 8080
---
